spring:
  cloud:
    gateway:
      routes:
        - id: baidu-test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: csdn-test
          uri: https://blog.csdn.net
          predicates:
            - Path=/common