spring:
  cloud:
    gateway:
      routes:
        - id: baidu-test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: csdn-test
          uri: https://blog.csdn.net
          predicates:
            - Path=/common
        - id: renren-fast
          uri: http://localhost:8082/
          predicates:
            - Path=/renren
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/renren-fast$\{segment}