spring:
  cloud:
    gateway:
      routes:
        - id: baidu-test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: csdn-test
          uri: https://blog.csdn.net
          predicates:
            - Path=/common
        - id: renren-fast
          uri: http://localhost:8082/
          predicates:
            - Path=/renren

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*) , /$\{segment}
        - id: aliyun_oss
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*) , /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*) , /renren-fast$\{segment}

    loadbalancer:
      ribbon:
        enabled: false
#    nacos:
#      config:
#        server-addr: 47.113.146.180:8848